version: "3.8"

services:
  menu-db:
    image: postgres:16-alpine
    container_name: menu-exam-db
    environment:
      POSTGRES_DB: db_menu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - menu-db-data:/var/lib/postgresql/data
    networks:
      - microservicios-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_menu"]
      interval: 10s
      timeout: 5s
      retries: 5

  orders-db:
    image: postgres:16-alpine
    container_name: orders-exam-db
    environment:
      POSTGRES_DB: db_orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    networks:
      - microservicios-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_orders" ]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-db:
    image: postgres:16-alpine
    container_name: inventory-exam-db
    environment:
      POSTGRES_DB: db_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    networks:
      - microservicios-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_inventory" ]
      interval: 10s
      timeout: 5s
      retries: 5

  menu-service:
    build:
      context: ./svc-menu
      dockerfile: Dockerfile
    container_name: menu-exam-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://menu-db:5432/db_menu
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
    networks:
      - microservicios-network
    depends_on:
      menu-db:
        condition: service_healthy

  orders-service:
    build:
      context: ./svc-orders
      dockerfile: Dockerfile
    container_name: orders-exam-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://orders-db:5432/db_orders
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8082"
    networks:
      - microservicios-network
    depends_on:
      orders-db:
        condition: service_healthy
      menu-service:
        condition: service_started
      inventory-service:
        condition: service_started

  inventory-service:
    build:
      context: ./svc-inventory
      dockerfile: Dockerfile
    container_name: inventory-exam-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/db_inventory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8083:8083"
    networks:
      - microservicios-network
    depends_on:
      inventory-db:
        condition: service_healthy

  nginx-gateway:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - microservicios-network
    depends_on:
      - menu-service
      - orders-service
      - inventory-service

volumes:
  menu-db-data:
  orders-db-data:
  inventory-db-data:
networks:
  microservicios-network:
    driver: bridge
