spring.application.name=svc-orders
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5434/db_orders
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info

#URL de comunicacion (svc-catalogo)
menu.service.url=http://menu-service:8081