events {
    worker_connections 1024;
}

http {

    upstream menu-service {
        server menu-service:8081;
    }

    upstream orders-service {
        server orders-service:8082;
    }

    upstream inventory-service {
        server inventory-service:8083;
    }

    server {
        listen 80;

        location /api/menu {
            proxy_pass http://menu-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/orders {
            proxy_pass http://orders-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/inventory {
            proxy_pass http://inventory-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /health {
            return 200 '{"status":"UP","service":"api-gateway"}';
            add_header Content-Type application/json;
        }
    }
}
